import React from "react"
import { AvatarGroup } from "./AvatarGroup"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  AvatarGroup,
  "https://www.figma.com/design/oFYEcVUdADBcqfEzrJs0Uc/%F0%9F%8C%8E-Global-Components?node-id=7917%3A16127",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "avatars": figma.enum(' Avatars', {
      //   "2": "2",
      //   "3": "3",
      //   "4": "4",
      //   "5": "5"
      // }),
      // "hasExtras": figma.boolean('Has Extras')
    },
    example: (props) => <AvatarGroup avatars={/* TODO */} />,
  },
)
